// src/components/Lightsaber.vue
<template>
    <div class="lightsaber" id="lightsaber">
        <div class="light-container" id="ligh-container">
            <div class="light" id="light"></div>
        </div>
        <img src="../assets/saber.png" alt="">
    </div>
</template>

<script>
export default {
    name: 'Lightsaber',
    data(){
      return{
          hola: 500,
          scrollBefore: 0
      }  
    },
    methods:{
        scrollIndicator(){
            var winScroll = document.body.scrollTop || document.documentElement.scrollTop;
            var height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
            var scrolled = (winScroll / height) * 100;       

            document.getElementById("ligh-container").style.height = 70 - ((scrolled * 70 )/100) + "vh";
        }
    },
    mounted(){  
        document.addEventListener('scroll', ()=>{        
            this.scrollIndicator()
        })
    }
}
</script>

<style scoped>
.lightsaber{
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    height: 90vh;
}

img{
    height: 10vh;
    z-index: 1;
}

.light-container{
    height: 70vh;
    z-index: -1;
    display: flex;
}

.light{
    width: 5px;
    background-color: #2fceb3;
    border-radius: 5px 5px 0 0; 
    /*BOX SHADOW*/
    box-shadow: 0px 0px 10px 5px rgba(50,206,179,0.75);
    -webkit-box-shadow: 0px 0px 10px 5px rgba(50,206,179,0.75);
    -moz-box-shadow: 0px 0px 10px 5px rgba(50,206,179,0.75);
}

</style>

// react-portfolio/src/components/Lightsaber/Lightsaber.jsx
import PropTypes from 'prop-types'
import { useEffect } from 'react'

import styles from './Lightsaber.module.css'
import handle from '../../assets/handle.png'

export default function Lightsaber({ className }){

    useEffect(()=>{
        console.log('Component is mounted')
        window.addEventListener('scroll', scrollIndicator);
    },[]);

    const scrollIndicator = () => {
        var winScroll = document.body.scrollTop || document.documentElement.scrollTop;
        var height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
        var scrolled = (winScroll / height) * 100;       

        var width =  document.documentElement.clientWidth;
        if(width < 800){
            document.getElementById("ligh-container").style.height = 75 - ((scrolled * 75 )/100) + "vh";
        }else{
            document.getElementById("ligh-container").style.height = 70 - ((scrolled * 70 )/100) + "vh";
        }
        
    }

    return(
        <div className={`${styles.lightsaber} ${className}`} id="lightsaber">
            <div className={styles.light_container} id="ligh-container">
                <div className={styles.light} id="light"></div>
            </div>
            <img src={handle} alt="sword handle" />
        </div>
    )
}

Lightsaber.propTypes = {
    className: PropTypes.string
}
